export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_INTRO = "CHANGE_INTRO";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_CONTACT = "CHANGE_CONTACT";
export const CHANGE_URL = "CHANGE_URL";
export const CHANGE_ADRESS = "CHANGE_ADRESS";
export const CHANGE_IMAGE = "CHANGE_IMAGE";
export const CHANGE_SUMMARY = "CHANGE_SUMMARY";
